import sys

def solve():
    input = sys.stdin.buffer.readline

    n, w = map(int, input().split())
    energy = [0] + list(map(int, input().split()))

    # Each line is represented as (slope, intercept)
    # y = m*x + b
    lines = []

    def value(line, x):
        m, b = line
        return m * x + b

    def bad(l1, l2, l3):
        # Remove l2 if intersection(l1,l2) >= intersection(l2,l3)
        m1, b1 = l1
        m2, b2 = l2
        m3, b3 = l3

        return (b2 - b1) * (m2 - m3) >= (b3 - b2) * (m1 - m2)

    # Night 1 must be active.
    dp = [0] * (n + 1)
    dp[1] = energy[1]

    # Line corresponding to j = 1
    # m = -2*w*j
    # b = dp[j] + w*j^2
    lines.append((-2 * w, dp[1] + w))

    head = 0

    for i in range(2, n + 1):

        # Since x=i is increasing, discard lines that
        # are worse than the next line.
        while head + 1 < len(lines):
            if value(lines[head], i) >= value(lines[head + 1], i):
                head += 1
            else:
                break

        best = value(lines[head], i)

        dp[i] = energy[i] + w * i * i + best

        # Add the line generated by night i.
        new_line = (
            -2 * w * i,
            dp[i] + w * i * i
        )

        while len(lines) - head >= 2 and bad(
            lines[-2], lines[-1], new_line
        ):
            lines.pop()

        lines.append(new_line)

    print(dp[n])


if __name__ == "__main__":
    solve()
